filmdistribution:
    version: Version @project.version@
    autologin: false
logging:
    level:
        org:
            atmosphere: warn
server:
    port: ${PORT:8080}
spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@//h2922093.stratoserver.net:1521/orcl.stratoserver.net
        username: video
        password: Gruppe2
    jpa:
        database-platform: org.hibernate.dialect.OracleDialect
        defer-datasource-initialization: true
        hibernate:
            enable_lazy_load_no_trans: true
            ddl-auto: none
    mustache:
        check-template-location: false
    sql:
        init:
            mode: always
vaadin:
    frontend:
        hotdeploy: true
    launch-browser: true
    whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.bbs.filmdistribution,com.github.appreciated.apexcharts
