CREATE TABLE application_user
(
    id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    username        nvarchar2(60),
    name            nvarchar2(30),
    hashed_password nvarchar2(1000),
    user_role       nvarchar2(30) default 'USER',
    CONSTRAINT application_user_pk PRIMARY KEY (id)
);


CREATE TABLE customer
(
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name          nvarchar2(30),
    first_name    nvarchar2(30),
    date_of_birth date,
    address       nvarchar2(255),
    zip_code      nvarchar2(10),
    city          nvarchar2(60),
    CONSTRAINT customer_pk PRIMARY KEY (id)
);


CREATE TABLE age_group
(
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name        nvarchar2(100),
    minimum_age number(3),
    CONSTRAINT age_group_pk PRIMARY KEY (id)
);


CREATE TABLE film
(
    id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name         nvarchar2(100),
    length       number(5),
    age_group_id number,
    price        number(4, 2),
    CONSTRAINT film_pk PRIMARY KEY (id),
    CONSTRAINT film_fk_age_group FOREIGN KEY (age_group_id) REFERENCES age_group (id)
);


CREATE TABLE film_copy
(
    id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    inventory_number nvarchar2(100),
    film_id          number,
    CONSTRAINT film_copy_pk PRIMARY KEY (id)
);


CREATE TABLE film_distribution
(
    id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    customer_id number,
    start_date  date,
    end_date    date,
    CONSTRAINT film_distribution_pk PRIMARY KEY (id),
    CONSTRAINT film_distribution_fk_customer FOREIGN KEY (customer_id) REFERENCES customer (id)
);


CREATE TABLE film_distribution_items
(
    film_distribution_id number,
    film_copy_id         number,
    CONSTRAINT film_distribution_items_pk PRIMARY KEY (film_distribution_id, film_copy_id),
    CONSTRAINT film_distribution_items_fk_film_distribution FOREIGN KEY (film_distribution_id) REFERENCES film_distribution (id),
    CONSTRAINT film_distribution_items_fk_film_copy FOREIGN KEY (film_copy_id) REFERENCES film_copy (id)
);